### ISSUE TITLE
感觉这个只是管理路由的工具，可以和fluro整合吗？

### ISSUE THREAD

**Issue by fengqiangboy** [alibaba-flutter/annotation_route#1]
感觉这个只是管理路由的工具，可以和fluro整合吗？
用fluro实现导航，通过annotation_route管理页面

**Comment by voicewitness** [comment]
fluro和annotation_route的结合目前可以通过以下方式实现：
`class MyRouter extends fluro.Router {
    ARouterInternal _internal = ARouterInternalImpl()
    @override
    Future navigateTo(BuildContext context, String path,
      {bool replace = false,
      bool clearStack = false,
      TransitionType transition,
      Duration transitionDuration = const Duration(milliseconds: 250),
      RouteTransitionsBuilder transitionBuilder}) {
     ARouteResult result = _internal.findPage(ARouteOption(url: path));
    if(result.state == ARouterResultState.FOUND) {
        Navigator.push(MaterialPageRoute(builder: (BuildContext context) {
            return result.widget;
        }));
    }
}`
在fluro开始导航前先使用annotation_route找到合适的页面

**Comment by voicewitness** [comment]
如果没有其他讨论进行的话，我会在近期内关闭该issue
