### ISSUE TITLE
这个库是否是纯净的，是否承诺没有彩蛋

### ISSUE THREAD

**Issue by VinciShark** [alibaba-flutter/annotation_route#2]

**Comment by voicewitness** [comment]
我们所有的更新均会体现在更新日志中，不会给使用者带来未经公布的变更。由于不同使用者对“彩蛋”的理解不同，我们建议使用者对于新版本中有异议的部分向我们提出issue，我们可以对相关issue进行讨论和更新；同时建议使用者在引用该库时**限定版本号**，以避免自动版本更新引入的不符合使用者期望的更新。

**Comment by liraku** [comment]
哥们 你是真的秀

**Comment by alvin198761** [comment]
作为一个局外人，大家都是通过antd 获得好处的人，免费开源，你享受了好处，还这么多屁话，有意思么，

**Comment by csshuai** [comment]
乾杯 []~（￣▽￣）~*

**Comment by asjqkkkk** [comment]
哈哈哈哈哈，嗝~
