### ISSUE TITLE
请问路由注解如何实现登录验证

### ISSUE THREAD

**Issue by yueqianzhang** [alibaba-flutter/annotation_route#5]
使用类似@login_required这样的注解  
直接写在路由上  
或者写在Page上

**Comment by OsBelief** [comment]
@yueqianzhang  ARouterInternalImpl里匹配page成功时返回的ARouterResult有interceptor，但是在ARoute里没有对interceptor的注解，应该是还没有实现这个功能，不知道以后会不会实现
